config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  post 'send_sms', to: 'users#send_sms'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :phone_number, presence: true, 
                         format: { with: /\A\d+\z/, message: "must be a number." }, 
                         length: { is: 10 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def send_sms
    phone_number = params[:phone_number]
    joke = IcanhasdadjokesService.new.get_joke
    # Use Twilio to send the joke to the provided phone number
    send_sms_message(phone_number, joke)

    redirect_to root_path, notice: "Text-illent job! Your dad joke has been sent!"

  rescue Twilio::REST::RestError => e
    flash[:error] = "That phone number format sure did a 'number' on us! Please try again."
    redirect_to root_path # replace this with your error path
  end

  private

  def send_sms_message(phone_number, message)
    client = Twilio::REST::Client.new(ENV['TWILIO_ACCOUNT_SID'], ENV['TWILIO_API_KEY'])

    client.messages.create(
      from: '+18448459414', 
      to: phone_number,
      body: message
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DadJokeDaddy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |type, msg| %>
  <p style="color: #EB455F; font-size: 30px"><%= msg %></p>
  <% end %>
  <br>

    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pirate Daddy</title>
  <style>
    body {
      background-image: url("https://imgflip.com/s/meme/Rick-and-Carl-Long.jpg");
      background-repeat: repeat;
      background-size: cover;
      color: #D9F7F2;
      text-align: center;
      font-family: 'Arial', sans-serif;
    }

    h1 {
      font-size: 40px;
      margin-top: 100px;
      text-shadow: 2px 2px 4px #000000;
      display: inline-block;
      padding: 10px;
    }

    h1 span {
      border: 1px solid black;
      padding: 5px;
      border-radius: 5px;
    }

    h2 {
      font-size: 30px;
      margin-bottom: 50px;
      text-shadow: 2px 2px 4px #000000;
      display: inline-block;
      padding: 3px;
    }

    h3 span {
      border: 1px solid black;
      padding: 5px;
      border-radius: 5px;
    }
    
    .pun-form {
      background: rgba(244, 241, 224, 0.85);;
      border-radius: 15px;
      width: 500px;
      margin: auto;
      padding: 20px;
      box-shadow: 5px 10px 18px #888888;
    }

    .pun-form-body {
      display: flex;
      flex-direction: column;
    }

    .form-group {
      margin-bottom: 20px;
    }

    .pun-form-label {
      color: #116A7B;
      font-family: 'Comic Sans MS', cursive, sans-serif;
      font-size: 20px;
      font-family: 'Arial', sans-serif;
    }

    .pun-form-input {
      border: none;
      height: 40px;
      border-radius: 5px;
      padding: 5px;
      font-size: 18px;
      margin-top: 10px;
      box-shadow: 3px 3px #888888;
      font-family: 'Arial', sans-serif;
    }

    .pun-form-button {
      background-color: #116A7B;
      color: white;
      border: none;
      border-radius: 15px;
      padding: 10px 20px;
      font-size: 20px;
      cursor: pointer;
      transition: background-color 0.3s ease;
      font-family: 'Comic Sans MS', cursive, sans-serif;
      box-shadow: 3px 3px #888888;
      font-family: 'Arial', sans-serif;
    }

    .pun-form-button:hover {
      background-color: #79B7C1;
    }
  </style>
</head>
<body>
  <h1>Dad Joke Daddy</h1>
	<br>
  <h2>Enter a phone number to recieve a random dad joke</h2>
  

  <div class="pun-form">
    <%= form_with url: send_sms_path, method: :post, local: true, html: {class: "pun-form-body"} do |f|%>
      <div>
      <div class="form-group">
        <%= f.label :phone_number, "Phone number example 15554320123", class: "pun-form-label" %>
        <%= f.text_field :phone_number, required: true, class: "pun-form-input" %>
      </div>
      <%= f.submit 'Prepare for Pun-ishment!', class: "pun-form-button" %>
    <% end %>
  </div>

</body>
</html>